export const CONTINENTS = {
  all: { name: 'הכל', emoji: '🌍' },
  asia: { name: 'אסיה', emoji: '🏯' },
  europe: { name: 'אירופה', emoji: '🏰' },
  americas: { name: 'אמריקה', emoji: '🗽' },
  oceania: { name: 'אוקיאניה', emoji: '🏝️' },
  africa: { name: 'אפריקה', emoji: '🦁' },
} as const;

export const COUNTRY_CONTINENTS: Record<string, keyof typeof CONTINENTS> = {
  IL: 'asia',
  TH: 'asia',
  IN: 'asia',
  JP: 'asia',
  CN: 'asia',
  KR: 'asia',
  VN: 'asia',
  ID: 'asia',
  MY: 'asia',
  SG: 'asia',
  PH: 'asia',
  TW: 'asia',
  HK: 'asia',
  AE: 'asia',
  SA: 'asia',
  TR: 'asia',

  GB: 'europe',
  FR: 'europe',
  DE: 'europe',
  IT: 'europe',
  ES: 'europe',
  PT: 'europe',
  NL: 'europe',
  BE: 'europe',
  CH: 'europe',
  AT: 'europe',
  GR: 'europe',
  SE: 'europe',
  NO: 'europe',
  DK: 'europe',
  FI: 'europe',
  PL: 'europe',
  CZ: 'europe',
  HU: 'europe',
  RO: 'europe',
  IE: 'europe',

  US: 'americas',
  CA: 'americas',
  MX: 'americas',
  BR: 'americas',
  AR: 'americas',
  CL: 'americas',
  CO: 'americas',
  PE: 'americas',
  EC: 'americas',
  CR: 'americas',
  PA: 'americas',

  AU: 'oceania',
  NZ: 'oceania',
  FJ: 'oceania',

  EG: 'africa',
  ZA: 'africa',
  MA: 'africa',
  KE: 'africa',
  TZ: 'africa',
  UG: 'africa',
  RW: 'africa',
  ET: 'africa',
};

export function getContinentForCountry(countryCode: string): keyof typeof CONTINENTS {
  return COUNTRY_CONTINENTS[countryCode] || 'all';
}
